from flask import Flask, render_template, jsonify
import json

app = Flask(__name__)

# Load JSON report generated by your MediSafe code
def load_report():
    with open("shipment_summary.json", "r") as f:
        return json.load(f)

@app.route("/")
def index():
    shipments = load_report()
    return render_template("index.html", shipments=shipments)

@app.route("/api/shipments")
def shipments_api():
    # Return JSON directly for API
    return jsonify(load_report())

if __name__ == "__main__":
    app.run(debug=True)
